# Configuration File for Harvest API
# ==================================
# This configuration file is used to set up and manage the various components of the Harvest API.
# It includes settings for database connections, API binding, logging, and silo configurations.

# Default MongoDB Configuration
# -----------------------------
# This section defines the default settings for MongoDB instances used in the application.
# Each MongoDB instance configuration includes prompts for the user to input necessary details.
.default-mongo: &default-mongo
  engine:
    default: mongo
  host:
    prompt: |
      Please enter the hostname or IP address for the Mongo instance which will store core application data.
      The default is `harvest-mongo`, which is the hostname of the Mongo instance in the Docker network
    default: harvest-mongo
  port:
    prompt: Please enter the port for the Mongo instance
    default: 27017
  database:
    prompt: Please enter the database name for the Mongo instance
    default: harvest
  username:
    prompt: Please enter the username for the Mongo instance
    default: harvest-api
  password:
    prompt: Please enter the password for the Mongo instance
    default: default-harvest-password
  authentication-database:
    prompt: Please enter the authentication database for the Mongo instance
    default: harvest

# Default Redis Configuration
# ----------------------------
# This section defines the default settings for Redis instances used in the application.
# Each Redis instance configuration includes prompts for the user to input necessary details.
.default-redis: &default-redis
  engine:
      default: redis
  host:
    prompt: |
      Please enter the hostname or IP address for the Redis instance which will store information.
      The default is `harvest-redis`, which is the hostname of the Redis instance in the Docker network
    default: harvest-redis
  port:
    prompt: Please enter the port for the Redis instance
    default: 6379
  database:
    prompt: Please enter the database number for the Redis instance
    default: 0
  password:
    prompt: Please enter the password for the Redis instance
    default: default-harvest-password

# API Configuration
# -----------------
# This section provides configurations specific to the binding address and port for the API.
api:
  .description: This section provides configurations specific to the binding address and port for the API.

  host:
    prompt: Please enter the binding address for the API
    default: 0.0.0.0
  port:
    prompt: Please enter the binding API port
    default: 8000

# Logging Configuration
# ---------------------
# This section provides configurations specific to the logging level and file path for the API.
logging:
    .description: This section provides configurations specific to the logging level and file path for the API
    level:
      prompt: Please enter the logging level for the API
      choices: [DEBUG, INFO, WARNING, ERROR, CRITICAL]
      default: DEBUG
    file:
      prompt: Please enter the directory path for the API log file
      default: ./app/logs/

# Silo Configuration
# There are 5 standard silos:
# Name                   | Engine | Purpose
# -----------------------|--------|---------
# `harvest-core`         | Mongo  | This is the primary data store for the Harvest API.
# `harvest-jobs`         | Redis  | This shows active and queued tasks that executors process.
# `harvest-nodes`        | Redis  | Where task executors and API nodes register themselves.
# `harvest-tokens`       | Redis  | Ephemeral user tokens.

silos:
  # Mongo - these backends are used to store persistent data
  harvest-core:
    .description: This silo is the primary data store for the Harvest API. It contains metadata records for information retrieved with data collection tasks.
    <<: *default-mongo

  # Redis - these backends are used to store ephemeral data

  harvest-nodes:
    .description: This silo is used to store information about agent and api nodes.
    <<: *default-redis
    database:
      prompt: Please enter the database number for the Redis instance
      default: 0

  harvest-jobs:
    .description: This silo is used to store information about active and queued tasks.
    <<: *default-redis
    database:
      prompt: Please enter the database number for the Redis instance
      default: 1

  harvest-tokens:
    .description: This silo is used to store ephemeral user tokens.
    <<: *default-redis
    database:
      prompt: Please enter the database number for the Redis instance
      default: 2
