# Configuration File for Harvest API
# ==================================
# This configuration file is used to set up and manage the various components of the Harvest API.
# It includes settings for database connections, API binding, logging, and silo configurations.

# Default MongoDB Configuration
# -----------------------------
# This section defines the default settings for MongoDB instances used in the application.
# Each MongoDB instance configuration includes prompts for the user to input necessary details.
.default-mongo: &default-mongo
  engine:
    default: mongo
  host:
    prompt: Hostname or IP address
    default: harvest-mongo
  port:
    prompt: Mongo port
    default: 27017
  database:
    prompt: Database name
    default: harvest
  username:
    prompt: Username
    default: harvest-api
  password:
    prompt: Password
    default: default-harvest-password
  authentication-database:
    prompt: Auth database
    default: harvest

# Default Redis Configuration
# ----------------------------
# This section defines the default settings for Redis instances used in the application.
# Each Redis instance configuration includes prompts for the user to input necessary details.
.default-redis: &default-redis
  engine:
      default: redis
  host:
    prompt: Hostname or IP address
    default: harvest-redis
  port:
    prompt: Redis port
    default: 6379
  database:
    prompt: Database number
    default: 0
  password:
    prompt: Password
    default: default-harvest-password

# API Configuration
# -----------------
# This section provides configurations specific to the binding address and port for the API.
api:
  .description: This section provides configurations specific to the binding address and port for the API.

  host:
    prompt: Binding address
    default: 0.0.0.0
  port:
    prompt: API port
    default: 8000

# Logging Configuration
# ---------------------
# This section provides configurations specific to the logging level and file path for the API.
logging:
    .description: This section provides configurations specific to the logging level and file path for the API
    level:
      prompt: Logging level
      choices: [DEBUG, INFO, WARNING, ERROR, CRITICAL]
      default: DEBUG
    file:
      prompt: Log file directory
      default: ./app/logs/

# Silo Configuration
# There are 5 standard silos:
# Name                   | Engine | Purpose
# -----------------------|--------|---------
# `harvest-core`         | Mongo  | This is the primary data store for the Harvest API.
# `harvest-jobs`         | Redis  | This shows active and queued tasks that executors process.
# `harvest-nodes`        | Redis  | Where task executors and API nodes register themselves.
# `harvest-tokens`       | Redis  | Ephemeral user tokens.
# `harvest-users`        | Mongo  | User and authentication configurations.

silos:
  # Mongo - these backends are used to store persistent data
  harvest-core:
    .description: This silo is the primary data store for the Harvest API. It contains metadata records for information retrieved with data collection tasks.
    <<: *default-mongo

  harvest-users:
    .description: This silo contains user information and authentication configurations.
    <<: *default-mongo
    database:
      prompt: Database name
      default: users

  # Redis - these backends are used to store ephemeral data
  harvest-nodes:
    .description: This silo is used to store information about agent and api nodes.
    <<: *default-redis
    database:
      prompt: Database number
      default: 0

  harvest-jobs:
    .description: This silo is used to store information about active and queued tasks.
    <<: *default-redis
    database:
      prompt: Database number
      default: 1

  harvest-tokens:
    .description: This silo is used to store ephemeral user tokens.
    <<: *default-redis
    database:
      prompt: Database number
      default: 2