# version:

services:
  api:
    image: cloud-harvest-api
    build:
      context: ./var/log/mongodb
      dockerfile: Dockerfile
      ssh:
        - default
    ports:
      - "8000:8000"
    stop_signal: SIGINT
    volumes:
      - "~/.ssh:/root/.ssh"
      - "~/.harvest/:/etc/harvest.d"
    working_dir: /src
    expose:
      - "8000"
