# version:

services:
  api:
    image: cloud-harvest-api
    build:
      dockerfile: Dockerfile
      ssh:
        - default
    ports:
      - "8000:8000"
    stop_signal: SIGINT
    volumes:
      - "~/.ssh:/root/.ssh"
      - "./app/:/src/app/"
    working_dir: /src
    user: "${UID}:${GID}"
    expose:
      - "8000"
